"""
filter_hallucinations.py — Tier D5 (Cross-Modal Grounding, v2)
==============================================================
Filters VQA-E annotations by checking whether the explanation is grounded
in what is actually visible in the image, using Faster R-CNN detected labels
as the ground truth visual scene description.

DEFINITION OF HALLUCINATION (visual, not textual)
--------------------------------------------------
A VQA-E explanation hallucinates when it mentions concrete objects that are
NOT detected in the image by the visual detector.  Example:

  Image: [person, bicycle, road]
  Question: "What is the man doing?"
  Explanation: "he is walking his dog near a pond"
               ^^^^                    ^^^^^^^^^^^
               Neither "dog" nor "pond" appear in the detected scene.
  → DISCARD: unsupported_visual_hallucination

Text-only heuristics (NER, copy-of-question) cannot catch this because they
have no access to what is actually in the image.

PRIMARY FILTER — Cross-Modal Visual Grounding
---------------------------------------------
1. Extract all concrete NOUNs from the explanation using spaCy (lemmatized,
   lowercase, non-stopword).
2. Look up the image's detected object labels from faster_rcnn_objects.json.
3. Compute the intersection.
4. If the explanation contains ≥ 1 concrete noun AND the intersection is
   empty → unsupported_visual_hallucination → discard.

SECONDARY FILTERS (text-only, applied after visual check)
----------------------------------------------------------
  too_short     : explanation after "because" is < 4 words
  copy_of_question : ≥ 80% token overlap between explanation and question

INPUTS
------
  --vqae_json    : path to VQA-E_train_set.json
  --rcnn_json    : path to faster_rcnn_objects.json (see format below)
  --output       : path to write filtered JSON
  --min_nouns    : min concrete nouns required before visual check triggers (default 1)
  --report       : print per-reason removal counts

faster_rcnn_objects.json FORMAT
--------------------------------
A flat dict mapping img_id (string or int) to list of detected COCO class
label strings (lowercase, singular, COCO 80-class vocabulary):

  {
    "123456": ["person", "dog", "frisbee", "grass"],
    "654321": ["car", "bus", "traffic light", "person"]
  }

Can be generated by:
  python src/scripts/extract_rcnn_labels.py \\
      --image_dir data/images \\
      --output    data/faster_rcnn_objects.json

Or from the already-extracted BUTD features (which store objectness scores
but not class labels); in that case run detection with --save_labels flag.

Usage
-----
  pip install spacy
  python -m spacy download en_core_web_sm

  python src/scripts/filter_hallucinations.py \\
      --vqae_json  data/annotations/vqa_e/VQA-E_train_set.json \\
      --rcnn_json  data/faster_rcnn_objects.json \\
      --output     data/annotations/vqa_e/VQA-E_train_filtered.json \\
      --report

  # Without rcnn_json (falls back to text-only secondary filters):
  python src/scripts/filter_hallucinations.py \\
      --vqae_json  data/annotations/vqa_e/VQA-E_train_set.json \\
      --output     data/annotations/vqa_e/VQA-E_train_filtered.json \\
      --report
"""

import json
import argparse
import re
from collections import Counter


# ── spaCy (required for noun extraction) ──────────────────────────────────────

try:
    import spacy as _spacy
    _NLP = None   # lazy-loaded on first use

    def _get_nlp():
        global _NLP
        if _NLP is None:
            _NLP = _spacy.load('en_core_web_sm')
        return _NLP

    SPACY_AVAILABLE = True
except ImportError:
    SPACY_AVAILABLE = False


# ── Constants ──────────────────────────────────────────────────────────────────

# Minimum words in explanation after "because" for it to be kept
_MIN_EXPLANATION_WORDS = 4

# Minimum concrete-noun count in explanation before visual grounding check fires.
# If the explanation has zero concrete nouns (e.g. "yes it is") we cannot do
# cross-modal grounding, so we skip the visual check for that explanation.
_DEFAULT_MIN_NOUNS_FOR_VISUAL_CHECK = 1

# COCO 80-class labels (lowercase singular) — used to normalize detected labels
# and to decide whether a noun is "concrete" enough to trigger the visual check.
# We do NOT hard-code a whitelist; instead we rely on the rcnn_json labels.

# Abstract/function nouns that appear often in explanations but cannot be
# grounded visually — exclude from noun extraction to avoid false positives.
_ABSTRACT_NOUNS = {
    'time', 'way', 'thing', 'reason', 'fact', 'type', 'kind', 'part',
    'side', 'case', 'point', 'place', 'use', 'form', 'level', 'group',
    'number', 'lot', 'day', 'year', 'line', 'word', 'hand', 'end', 'home',
    'question', 'answer', 'image', 'photo', 'picture', 'scene',
}


# ── Noun extraction ────────────────────────────────────────────────────────────

def extract_concrete_nouns(text, nlp):
    """
    Return the set of concrete nouns in text, lemmatized and lowercased.
    Filters out stopwords, abstract nouns, and very short tokens.

    Args:
        text : str — explanation text
        nlp  : spaCy Language model

    Returns:
        set[str] — lemmatized concrete nouns
    """
    doc   = nlp(text)
    nouns = set()
    for token in doc:
        if (token.pos_ == 'NOUN'
                and not token.is_stop
                and len(token.lemma_) > 2
                and token.lemma_.lower() not in _ABSTRACT_NOUNS):
            nouns.add(token.lemma_.lower())
    return nouns


# ── Secondary text-only heuristics ────────────────────────────────────────────

def _tokenize(text):
    """Whitespace tokenizer used for overlap and length checks."""
    return re.findall(r"[a-z']+", text.lower())


def is_too_short(explanation_text):
    """Return True if the explanation (after 'because') is under 4 words."""
    parts      = explanation_text.lower().split('because', 1)
    after_part = parts[1].strip() if len(parts) > 1 else explanation_text
    return len(_tokenize(after_part)) < _MIN_EXPLANATION_WORDS


def is_copy_of_question(explanation_text, question_text, threshold=0.8):
    """Return True if ≥ 80% of explanation tokens appear in the question."""
    exp_tokens = set(_tokenize(explanation_text))
    q_tokens   = set(_tokenize(question_text))
    if not exp_tokens or not q_tokens:
        return False
    return len(exp_tokens & q_tokens) / len(exp_tokens) >= threshold


# ── Cross-modal visual grounding ───────────────────────────────────────────────

def normalize_label(label):
    """Lowercase and strip a detected class label for comparison."""
    return label.lower().strip()


def is_visually_unsupported(explanation_nouns, detected_labels, min_nouns=1):
    """
    Return True if the explanation mentions concrete objects that are not
    detected in the image by Faster R-CNN.

    Logic:
      - Requires at least `min_nouns` concrete nouns for the check to fire.
        Explanations with no concrete nouns (e.g. "yes because it is sunny")
        cannot be cross-modally grounded and are passed through.
      - Normalizes both sides: lemmatized nouns vs. normalized COCO labels.
      - If intersection is empty → hallucination.

    Args:
        explanation_nouns : set[str] — from extract_concrete_nouns()
        detected_labels   : set[str] — normalized COCO class labels for this image
        min_nouns         : int — minimum noun count before check fires

    Returns:
        bool
    """
    if len(explanation_nouns) < min_nouns:
        return False   # not enough nouns to ground — skip visual check
    if not detected_labels:
        return False   # no detection results for this image — cannot check
    intersection = explanation_nouns & detected_labels
    return len(intersection) == 0


# ── Per-annotation scoring ─────────────────────────────────────────────────────

def score_annotation(ann, rcnn_lookup, nlp=None, min_nouns=1):
    """
    Score a single VQA-E annotation.

    Primary check  : Cross-modal visual grounding (explanation nouns vs RCNN labels).
    Secondary checks: too_short, copy_of_question.

    The annotation is KEPT if at least one explanation passes all checks.
    The annotation is REMOVED only if ALL its explanations fail.

    Args:
        ann         : dict — one VQA-E annotation record
        rcnn_lookup : dict[str, set[str]] — img_id → set of normalized detected labels
                      Pass {} if no rcnn_json available (disables visual check).
        nlp         : spaCy model or None (disables noun extraction + visual check)
        min_nouns   : passed to is_visually_unsupported()

    Returns:
        keep    : bool
        reasons : list[str] — non-empty only when keep=False
    """
    question = ann.get('question', '')
    img_id   = str(ann.get('img_id', ''))
    exp_list = ann.get('explanation', [])
    valid_exps = [e for e in exp_list if isinstance(e, str) and e.strip()]

    # No explanation → keep unconditionally
    if not valid_exps:
        return True, []

    # Get detected labels for this image (empty set = visual check skipped)
    detected_labels = rcnn_lookup.get(img_id, set())

    reasons_per_exp = []

    for exp in valid_exps:
        reasons = []

        # ── PRIMARY: Cross-modal visual grounding ──────────────────────────
        if nlp is not None and detected_labels:
            nouns = extract_concrete_nouns(exp, nlp)
            if is_visually_unsupported(nouns, detected_labels, min_nouns):
                reasons.append('unsupported_visual_hallucination')

        # ── SECONDARY: text-only checks ────────────────────────────────────
        if is_too_short(exp):
            reasons.append('too_short')

        if is_copy_of_question(exp, question):
            reasons.append('copy_of_question')

        reasons_per_exp.append(reasons)

    # Keep if at least one explanation has no issues
    all_bad = all(bool(r) for r in reasons_per_exp)
    if all_bad:
        all_reasons = list({r for rs in reasons_per_exp for r in rs})
        return False, all_reasons
    return True, []


# ── rcnn_json loader ───────────────────────────────────────────────────────────

def load_rcnn_lookup(rcnn_json_path):
    """
    Load faster_rcnn_objects.json and return a dict:
      img_id_str → set of normalized (lowercase) label strings.

    Accepts both string and integer keys in the JSON.
    """
    with open(rcnn_json_path) as f:
        raw = json.load(f)
    lookup = {}
    for img_id, labels in raw.items():
        normalized = {normalize_label(lb) for lb in labels if lb}
        lookup[str(img_id)] = normalized
    return lookup


# ── CLI entry point ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description='Cross-modal hallucination filter for VQA-E annotations.')
    parser.add_argument('--vqae_json',  required=True,
                        help='Input VQA-E annotation JSON (e.g. VQA-E_train_set.json)')
    parser.add_argument('--rcnn_json',  default=None,
                        help='faster_rcnn_objects.json mapping img_id → detected labels. '
                             'If omitted, visual grounding check is skipped (text-only mode).')
    parser.add_argument('--output',    required=True,
                        help='Path to write filtered annotation JSON')
    parser.add_argument('--min_nouns', type=int, default=_DEFAULT_MIN_NOUNS_FOR_VISUAL_CHECK,
                        help='Min concrete nouns for visual check to fire (default 1)')
    parser.add_argument('--report',    action='store_true',
                        help='Print per-reason removal counts after filtering')
    args = parser.parse_args()

    # ── spaCy ──────────────────────────────────────────────────────────────
    if not SPACY_AVAILABLE:
        print("WARNING: spaCy not installed — both noun extraction and NER will be skipped.")
        print("Install with: pip install spacy && python -m spacy download en_core_web_sm")
        nlp = None
    else:
        print("Loading spaCy en_core_web_sm ...")
        nlp = _get_nlp()

    # ── RCNN lookup ────────────────────────────────────────────────────────
    rcnn_lookup = {}
    if args.rcnn_json is not None:
        print(f"Loading RCNN detections: {args.rcnn_json} ...")
        rcnn_lookup = load_rcnn_lookup(args.rcnn_json)
        print(f"  Loaded detections for {len(rcnn_lookup):,} images.")
    else:
        print("WARNING: --rcnn_json not provided — visual grounding check disabled.")
        print("  Only text-only secondary filters (too_short, copy_of_question) will run.")
        print("  For full cross-modal filtering, generate faster_rcnn_objects.json first.")

    # ── Load annotations ───────────────────────────────────────────────────
    print(f"Loading {args.vqae_json} ...")
    with open(args.vqae_json) as f:
        annotations = json.load(f)
    print(f"  {len(annotations):,} annotations loaded.")

    # ── Filter ────────────────────────────────────────────────────────────
    kept          = []
    removed       = 0
    reason_counts = Counter()
    no_detection  = 0   # images not in rcnn_lookup

    for ann in annotations:
        img_id = str(ann.get('img_id', ''))
        if rcnn_lookup and img_id not in rcnn_lookup:
            no_detection += 1

        keep, reasons = score_annotation(
            ann, rcnn_lookup, nlp=nlp, min_nouns=args.min_nouns)
        if keep:
            kept.append(ann)
        else:
            removed += 1
            reason_counts.update(reasons)

    # ── Report ────────────────────────────────────────────────────────────
    total = len(annotations)
    print(f"\nOriginal   : {total:,}")
    print(f"Kept       : {len(kept):,}  ({len(kept)/total:.1%})")
    print(f"Removed    : {removed:,}  ({removed/total:.1%})")
    if rcnn_lookup and no_detection:
        print(f"No RCNN hit: {no_detection:,} annotations had no detection entry "
              f"(visual check skipped for those)")

    if args.report:
        print("\nRemoval reasons:")
        for reason, cnt in reason_counts.most_common():
            pct = cnt / total * 100
            print(f"  {reason:<35} : {cnt:>6,}  ({pct:.1f}%)")
        print()
        if reason_counts.get('unsupported_visual_hallucination', 0):
            vcnt = reason_counts['unsupported_visual_hallucination']
            print(f"  → {vcnt:,} annotations removed by cross-modal visual grounding "
                  f"(primary filter)")
        txt = sum(v for k, v in reason_counts.items()
                  if k in ('too_short', 'copy_of_question'))
        if txt:
            print(f"  → {txt:,} annotations removed by text-only secondary filters")

    # ── Write output ──────────────────────────────────────────────────────
    import os
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, 'w') as f:
        json.dump(kept, f, indent=2)
    print(f"\nSaved filtered annotations → {args.output}")


if __name__ == '__main__':
    main()
